---
- hosts: digitalocean
  sudo: true
  user: root
  tasks:
    # Ping server
    - include: tasks/ping.yml

    # Write MOTD File
    - include: tasks/motd.yml

    # Update the PHP PPA Repository in Ubutntu to PHP 5.6
    - include: tasks/php-ppa-5.6-update.yml

    # Run apt-get update
    - include: tasks/apt-update.yml