---
- hosts: digitalocean
  sudo: true
  user: root
  tasks:
    # Ping server
    - include: tasks/ping.yml

    # Write MOTD File
    - include: tasks/motd.yml

    # Update the PHP PPA Repository in Ubutntu to PHP 5.6
    - include: tasks/php-ppa-5.6-update.yml

    # Run apt-get update
    - include: tasks/apt-update.yml

    # Force locale
    - include: tasks/locale.yml

    # Force Timezone
    - include: tasks/timezone.yml

    # Install vim
    - include: tasks/vim.yml

    # Install git
    - include: tasks/git.yml

    # Install curl
    - include: tasks/curl.yml

    # Install PHP & Extensions
    - include: tasks/php.yml

    # Enable PHP mcrypt extension
    - include: tasks/php-mcrypt.yml

    # Update Some PHP CLI Settings
    - include: tasks/php-cli-settings.yml

    # Install Composer
    - include: tasks/composer.yml